language: r
cache: packages
sudo: true
warnings_are_errors: true

r:
  - release
  - devel

env:
  global:
  - _R_CHECK_FORCE_SUGGESTS_=FALSE

r_github_packages:
  - jimhester/covr

after_success:
  - Rscript -e 'covr::codecov()'
